### ISSUE TITLE
Cannot authenticate with Google

### ISSUE THREAD

**Issue by Lothindir** [cheers-li/cheers-li-app#35]
**Describe the bug**
When trying to authenticate with Google, the app redirects on a empty page with written "Found."

**To Reproduce**
1. Click on 'I already have an account'
2. Click on 'Continue with Google'
3. See error

**Expected behavior**
The app shoulds authenticate and redirect to the homepage.

**Screenshots**
[Screenshot](https://prnt.sc/hICCbWTn1qol)

**Desktop (please complete the following information):**
 - OS: Android
 - Version 30

**Comment by MrF3lix** [comment]
Solved after reinstall. Don't know what happened but will open this again once we can reproduce it.
