### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by MrF3lix** [cheers-li/cheers-li-app#63]

**Comment by MrF3lix** [comment]
- Notification Settings
  - Select which notifications should be received (New Session, Friend Request, Cheersli, etc.)
- Location Settings => Link to System Settings
- Help => FAQ (or link to landing page with FAQ)
- About => Link to Repository, Privacy Policy, etc.
- Profile Settings => Change Username, Change bio, Change city

**Comment by vkaelin** [comment]
Should we add a web to choose between light and dark mode? (To override the system's preferences)

**Comment by vkaelin** [comment]
> Should we add a web to choose between light and dark mode? (To override the system's preferences)

I'll do that in #83
