### ISSUE TITLE
Disable Landscape orientation

### ISSUE THREAD

**Issue by vkaelin** [cheers-li/cheers-li-app#81]
Force portait orientation in the entire app for IOS and Android.

Doc: https://capacitorjs.com/docs/guides/screen-orientation

**Comment by ahmedsilat44** [comment]
Hey @vkaelin I would like to fix this issue. Can you assign it to me. Thanks 😄

**Comment by vkaelin** [comment]
> Hey @vkaelin I would like to fix this issue. Can you assign it to me. Thanks 😄

Thanks a lot! Done!
