### ISSUE TITLE
[Android] User can't send Cheers.li!'s after a session is started

### ISSUE THREAD

**Issue by LucaNeyer** [cheers-li/cheers-li-app#94]
**Describe the bug**
If a User A started a session, a user B on Android can press on Cheers.li! but USer A does not receive a notification.

**To Reproduce**
1. User A starts a session in the app
2. User B clicks on Cheers.li!
3. User A does not receive a notification.

**Expected behavior**
If User B presses Cheers.li!, User A should receive a push-notification.

**Desktop (please complete the following information):**
 - OS: Android

**Additional context**
Notifications work from iOS to Android.

**Comment by Lothindir** [comment]
Resolved
